# Squelch — RF / SDR signal platform
# Copyright (C) 2026  github.com/dawardy/squelch
# Licensed under GNU GPL v3 — see LICENSE.

from __future__ import annotations
"""Squelch -- core/survey_report.py

Human-readable report of a survey baseline comparison (ROADMAP §13.2). A hound
sweep that finds something should produce an artifact you can keep or hand off;
`core/rf_baseline.compare_baselines` yields a `BaselineDiff`, and this turns that
into a shareable **HTML** or **plain-text/markdown** report:

  * a header — title, when, location, reference→current labels, noise-floor
    delta, anomaly count,
  * *Appeared (anomalies)* — signals present now that the reference lacked
    (a new emitter: potential bug / tracker / unauthorized transmitter),
  * *Power changed* — signals whose peak shifted beyond tolerance,
  * *Vanished* — reference signals no longer present.

`diff_rows()` flattens a diff into plain dicts, reused by the HTML, text, and any
CSV/table consumer. All string fields are HTML-escaped at the render chokepoint
(the map-XSS lesson: never concatenate RF/network-derived strings into HTML raw).
Pure Python, no Qt, never raises.
"""

import html
import logging
from pathlib import Path

log = logging.getLogger(__name__)

_SECTIONS = (("new", "Appeared (anomalies)"),
             ("changed", "Power changed"),
             ("missing", "Vanished"))


# ── structured rows ─────────────────────────────────────────────────────────
def diff_rows(diff) -> list[dict]:
    """Flatten a BaselineDiff into display/CSV rows. Never raises."""
    rows: list[dict] = []
    if diff is None:
        return rows
    buckets = {"new": getattr(diff, "new", []),
               "changed": getattr(diff, "changed", []),
               "missing": getattr(diff, "missing", [])}
    for kind, items in buckets.items():
        for d in items or []:
            try:
                rows.append({
                    "kind":        kind,
                    "freq_mhz":    round(d.center_hz / 1e6, 6),
                    "bw_khz":      round(d.bandwidth_hz / 1e3, 3),
                    "peak_db":     round(d.peak_db, 1),
                    "ref_peak_db": round(d.ref_peak_db, 1),
                    "delta_db":    round(d.delta_db, 1),
                    "label":       d.label or "",
                    "category":    d.category or "",
                })
            except Exception as exc:                # pragma: no cover
                log.debug("survey_report: bad delta skipped: %s", exc)
    return rows


def _meta(diff, title, location, when) -> dict:
    return {
        "title":       title,
        "when":        when,
        "location":    location,
        "ref_label":   getattr(diff, "ref_label", "") or "(reference)",
        "cur_label":   getattr(diff, "cur_label", "") or "(current)",
        "floor_delta": getattr(diff, "floor_delta_db", 0.0),
        "anomalies":   getattr(diff, "anomaly_count", 0),
    }


# ── plain text / markdown ───────────────────────────────────────────────────
def diff_to_text(diff, *, title: str = "RF Survey Report",
                 location: str = "", when: str = "") -> str:
    """A plain-text/markdown report — good for logs, notes, quick sharing."""
    m = _meta(diff, title, location, when)
    lines = [m["title"], "=" * len(m["title"])]
    if m["when"]:
        lines.append(f"Generated: {m['when']}")
    if m["location"]:
        lines.append(f"Location:  {m['location']}")
    lines.append(f"Reference: {m['ref_label']}  ->  Current: {m['cur_label']}")
    lines.append(f"Noise floor delta: {m['floor_delta']:+.1f} dB")
    lines.append(f"Anomalies (appeared + changed): {m['anomalies']}")
    rows = diff_rows(diff)
    by_kind = {k: [r for r in rows if r["kind"] == k] for k, _ in _SECTIONS}
    for kind, heading in _SECTIONS:
        lines += ["", f"## {heading} ({len(by_kind[kind])})"]
        if not by_kind[kind]:
            lines.append("  (none)")
            continue
        for r in by_kind[kind]:
            tag = f"  {r['label']} [{r['category']}]".rstrip(" []") \
                if r["label"] or r["category"] else ""
            lines.append(
                f"  {r['freq_mhz']:.6f} MHz  BW {r['bw_khz']:.1f} kHz  "
                f"{r['peak_db']:+.1f} dB  (delta {r['delta_db']:+.1f}){tag}")
    lines += ["", "Generated by Squelch — verify before acting on any anomaly."]
    return "\n".join(lines)


# ── HTML ────────────────────────────────────────────────────────────────────
def diff_to_html(diff, *, title: str = "RF Survey Report",
                 location: str = "", when: str = "") -> str:
    """A self-contained (inline-CSS) HTML report — printable / shareable."""
    m = _meta(diff, title, location, when)
    e = html.escape
    rows = diff_rows(diff)
    head = (
        f"<h1>{e(m['title'])}</h1>\n<table class='meta'>"
        + (f"<tr><th>Generated</th><td>{e(m['when'])}</td></tr>" if m['when'] else "")
        + (f"<tr><th>Location</th><td>{e(m['location'])}</td></tr>" if m['location'] else "")
        + f"<tr><th>Reference</th><td>{e(m['ref_label'])}</td></tr>"
        + f"<tr><th>Current</th><td>{e(m['cur_label'])}</td></tr>"
        + f"<tr><th>Noise floor delta</th><td>{m['floor_delta']:+.1f} dB</td></tr>"
        + f"<tr><th>Anomalies</th><td>{m['anomalies']}</td></tr></table>")
    body = "".join(_html_section(kind, heading, rows) for kind, heading in _SECTIONS)
    return (f"<!doctype html><html><head><meta charset='utf-8'>"
            f"<title>{e(m['title'])}</title>{_CSS}</head><body>"
            f"{head}{body}"
            f"<p class='foot'>Generated by Squelch — verify before acting "
            f"on any anomaly.</p></body></html>")


def _html_section(kind: str, heading: str, rows: list[dict]) -> str:
    e = html.escape
    subset = [r for r in rows if r["kind"] == kind]
    out = [f"<h2 class='{kind}'>{e(heading)} ({len(subset)})</h2>"]
    if not subset:
        return out[0] + "<p class='none'>None.</p>"
    out.append("<table class='sig'><thead><tr>"
               "<th>Freq (MHz)</th><th>BW (kHz)</th><th>Peak (dB)</th>"
               "<th>&Delta; (dB)</th><th>Label</th><th>Category</th>"
               "</tr></thead><tbody>")
    for r in subset:
        out.append(
            "<tr>"
            f"<td class='num'>{r['freq_mhz']:.6f}</td>"
            f"<td class='num'>{r['bw_khz']:.1f}</td>"
            f"<td class='num'>{r['peak_db']:+.1f}</td>"
            f"<td class='num'>{r['delta_db']:+.1f}</td>"
            f"<td>{e(r['label'])}</td><td>{e(r['category'])}</td></tr>")
    out.append("</tbody></table>")
    return "".join(out)


# ── file output ─────────────────────────────────────────────────────────────
def write_report(diff, path, *, fmt: str = "html",
                 title: str = "RF Survey Report",
                 location: str = "", when: str = "") -> Path | None:
    """Render `diff` and write it to `path`. `fmt` is 'html' or 'text'.
    Returns the written Path, or None on failure. Never raises."""
    try:
        render = diff_to_text if str(fmt).lower() in ("text", "txt", "md") \
            else diff_to_html
        content = render(diff, title=title, location=location, when=when)
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        return p
    except Exception as exc:                         # pragma: no cover
        log.debug("survey_report write failed: %s", exc)
        return None


_CSS = """<style>
body{font-family:system-ui,Segoe UI,Arial,sans-serif;margin:24px;color:#222;background:#fff}
h1{font-size:20px;margin:0 0 12px}
h2{font-size:15px;margin:20px 0 6px;border-bottom:1px solid #ccc;padding-bottom:2px}
h2.new{color:#a11}h2.changed{color:#a60}h2.missing{color:#555}
table{border-collapse:collapse;margin:4px 0}
table.meta th{text-align:right;padding:2px 10px 2px 0;color:#555;font-weight:600}
table.sig{width:100%;font-size:13px}
table.sig th,table.sig td{border:1px solid #ddd;padding:3px 8px;text-align:left}
table.sig th{background:#f2f2f2}
td.num{text-align:right;font-variant-numeric:tabular-nums}
p.none{color:#888;margin:4px 0}
p.foot{margin-top:24px;color:#888;font-size:12px}
</style>"""
